In [1]:
import numpy as np

In [2]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
a[:3] = 5

In [4]:
a

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [5]:
mylist=list(range(10))
mylist

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
mylist[:3] = 100, 100, 100
mylist

[100, 100, 100, 3, 4, 5, 6, 7, 8, 9]

In [12]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [13]:
a_slice = a[:5]
a_slice

array([20, 21, 22, 23, 24])

In [14]:
a_slice[:3] = 5
a_slice

array([ 5,  5,  5, 23, 24])

In [15]:
a

array([ 5,  5,  5, 23, 24, 25, 26, 27, 28, 29])

In [16]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
a1 = a.copy()

In [19]:
a_slice = a1[:5]
a_slice

array([20, 21, 22, 23, 24])

In [20]:
a_slice[:3] = 5
a_slice

array([ 5,  5,  5, 23, 24])

In [21]:
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
a = np.random.randint(1, 100, 15)
a

array([89, 20, 65, 11, 79, 57, 46, 79, 60,  9, 29, 50, 90, 67, 56])

In [23]:
a < 50

array([False,  True, False,  True, False, False,  True, False, False,
        True,  True, False, False, False, False])

In [24]:
a[a < 50]

array([20, 11, 46,  9, 29])

In [25]:
a[(a<50) | (a>75)]

array([89, 20, 11, 79, 46, 79,  9, 29, 90])