**Recap_S2_Attribute_Index_Slice_01_08_22**

In [ ]:
import numpy as np

In [ ]:
np.arange(0,10,2) # girilen değerler arasında eleman üretir (start:, stop:, step:)

In [ ]:
np.linspace(1,20,num = 2) # girilen değerleri num parametresi kadar eşit aralığa böler (start:, stop:, num:) stop dahil

In [ ]:
np.linspace(1,[5,10], 5) # stop liste içinde verildiğinde 1 - 5 arası ve 1 - 10 arası eleman üretir.

In [ ]:
np.zeros(10, dtype= int)# girilen değer kadar sıfırlardan oluşan elemanlar üretir. dtype parametresi üretilecek eleman type'ı

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10, dtype= int)# girilen değer kadar bir'lerden oluşan elemanlar üretir. dtype parametresi üretilecek eleman type'ı

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.full(3,"test") # girilen sayı ve değer kadar eleman üretir

array(['test', 'test', 'test'], dtype='<U4')

In [ ]:
np.eye(5,5) # matris üretir

**RANDOM**

In [ ]:
np.random.rand(2,1,2) # uniform(olasılık oranı sabit) rastgele elemanlar üretir (num, size(satır, sutun))

In [ ]:
np.random.randn(1,3,4) #normal dağılıma(normal dist.) rastgele elemanlar üretir (num, size(satır, sutun))

In [ ]:
np.random.randint(1, [10,20], size= (2,2)) # rastgele  "int" elemanlar üretir (num, size(satır, sutun))

array([[ 5, 13],
       [ 5, 11]])

## **Array Attribute**

In [ ]:
arr = np.arange(10)
arr

In [ ]:
arr.shape # numpy array eleman sayısını verir

In [ ]:
arr.reshape(2,5) # dizinin şeklini değiştirmeden boyutnu değiştir. arka planda yeni boyut varmış gibi davranır. girilen değerlerin çarpımı array eleman sayısna eşit olmalıdır.

In [ ]:
arr.max() # array max. value

In [ ]:
arr.min() # array min. value

In [ ]:
arr.argmax() # array max. value index numarası

In [ ]:
arr.dtype # array eleman type

In [ ]:
arr.ndim # array boyut sayısı

In [ ]:
arr.size # array eleman sayısı

In [ ]:
arr.itemsize  # array eleman boyut

**ARRAY INDEXING & SLICE**

In [ ]:
a = np.arange(1,26).reshape(5,5)
a

In [ ]:
a = np.arange(1,26) # 1D array python index ve slice ile aynı

In [ ]:
a[1:, 2:4] # 2D array satır ve sutunlar seklinde seçme. 1 = satır index 2 = sutun index

In [ ]:
b = a[a>5] # condition işlemleri uygulanabilir.
b

In [ ]:
a < 4 # array'in elamanlarında condition operatörüen uyan değer true uymanay false

In [ ]:
a[(a> 15) | (a<5)] # condition operatörleri ile seçme

In [ ]:
x = np.arange(1,11)
y = np.arange(1,5)

In [ ]:
x

In [ ]:
y

In [ ]:
mat1 = np.arange(1,11)
mat2 = np.arange(1,11)

In [ ]:
mat1*mat2 # matematiksel işlemler uygulanabilir.

In [ ]:
np.concatenate((x,y)) # iki farklı array'i birleştirme